### ISSUE TITLE
Bot may post as another Reddit user

### ISSUE THREAD

**Issue by julianxhokaxhiu** [tecnoscimmie/tsredditbot#3]
As posting with the Bot in a reddit channel would behave the channel feeling as it's "maintained by bots", would be nice that who posts the link via the Bot is used also as a submitter of that link on reddit.

Would be nice to investigate if Reddit allows this, and if yes, provide a dedicated command to tell the bot which user I am on reddit.

Again this is matched through the UID of Telegram. For eg. this may be a dictionary payload inside the bot:
```
[
 {
  "uid": 12345,
  "ruser": "julianxhokaxhiu",
 }
]
```

where `uid` is the Telegram User ID, and `ruser` is the associated reddit user.

An example of private command would be:
```
/setRedditUser julianxhokaxhiu
```

**Comment by gsora** [comment]
IMHO, there are 2 main ways to deal with this proposal.

We can either

 - include the username in the post title. Something like "Posted by USERNAME | Page title"
 - let the bot authenticate and behave on behalf of the user

Since we can interact directly with the user through Telegram, letting him authenticate using OAuth2 is a feasible operation.

Since this is a pretty radical change, I don't think we can develop the entire flow in time for the [0.1](https://github.com/tecnoscimmie/tsredditbot/milestone/1).

**Comment by julianxhokaxhiu** [comment]
I prefer having the option to authenticate via oauth2 and let the bot post on my behalf.

Easier also to integrate in our reddits and groups too. Looking forward into it!
